### ISSUE TITLE
"No games available" appears 1,5 second

### ISSUE THREAD

**Issue by MaryPek** [ludobox/ludobox#103]
"No games available" appears 1,5 second when you click on browse games and also when you want returned to the main page after saw game's page details.

**Comment by MaryPek** [comment]
[Clemsos] Yes, this is because as we have more games, the data takes more time to load. The page will wait for the whole data to be loaded before displaying anything. The main problem here is that we still don’t have a database (we use plain files) so we can not optimise data request - with something like lazy loading. Basically, this will stay like that until we switch towards using a database

**Comment by tuxun** [comment]
Maybe it could shows <<Loading data...>> first, then after 1.5second<<No games available>> (or the result). 
You're using a raspberry pi, right? with a "good" sd card?

**Comment by clemsos** [comment]
@tuxun the main website runs on a VPS 

> Maybe it could shows <> first, then after 1.5second<> (or the result).

not sure what you mean here.   
For now we are parsing everything on the client. The main problem is that this JSON is toooo big https://box.ludobox.net/api/games . We are parsing relevant fields for the whole collection here https://github.com/ludobox/ludobox/blob/135c9bf2d12f2671655bcf46f3a3a75e28dad06a/server/ludobox/content.py#L200 so we can have a proper filter on the UI.

**Comment by tuxun** [comment]
Sorry,  @clemsos I messed up the markdown, @MaryPek  i didnt know this repo was including the website :)  

I meant:  first set the default value of text to "loading data", then, when result are computed , update the string with "no result" or show the result, that would delete the loading moment where  "no result" (while its computing) is shown.

Now I more a C guy, i think in c the solution for load big file would be to load and read it in multiple chunks. I don't know if its possible in python...
maybe for parsedir for infofile while (read_line(file)){info.append(...)}

Also It could works better to make the short test before the for loop and to run the appropriate info_files.append :
```
if short : 
     # loop through all folders (short=true)
     for item in os.listdir(current_app.config["DATA_DIR"]) : 
         path = os.path.join(current_app.config["DATA_DIR"],item) 
         # get only folders 
         if os.path.isdir(path): 
             info_file = os.path.join(path, "info.json") 

             # check if folder contains a info.json file 
             if os.path.exists(info_file): 
                 info = read_content(path) 
                 info_files.append({ k : info[k] for k in wanted_keys if k in info.keys() }) 

#parse folders (short=false)
else : 
     for item in os.listdir(current_app.config["DATA_DIR"]) : 
         path = os.path.join(current_app.config["DATA_DIR"],item) 
  
         # get only folders 
         if os.path.isdir(path): 
             info_file = os.path.join(path, "info.json")
             
             #check if folder contains a info.json file 
             if os.path.exists(info_file): 
                 info = read_content(path) 
                 info_files.append(info)
   
     sorted_info_files = sorted(info_files, key=lambda k: k['title']) 
return sorted_info_files
```

atm im reading [this link about readlines efficiency](https://stackoverflow.com/questions/17246260/python-readlines-usage-and-efficient-practice-for-reading) and [this](https://stackoverflow.com/questions/18517949/what-is-faster-loading-a-pickled-dictionary-object-or-loading-a-json-file-to) and maybe "json.load" isnt made for load/parse too big files in one pass

**Comment by clemsos** [comment]
@tuxun what mary meant was that the box.ludobox.net is deployed on a VPS. The website is at ludobox/ludobox.github.io 

> I meant: first set the default value of text to "loading data", then, when result are computed , update the string with "no result" or show the result,

Yes, sure. That is doable. 

For the rest, the JSON file is generated on-the-fly at each request. Again, no caching or optimization - the whole thing is very minimal. The goal ot the current architecture was to put all the load on the client as the server was weak by design. We wanted to minimize the number of requests to the server, so we have to do one big request at start.

So on the homepage, we need to send the **whole list of games** to the client so filters can be apply client-side. 

I guess a simple optimization will be to send the JSON minified.

<img width="561" alt="screen shot 2018-04-20 at 09 33 27" src="https://user-images.githubusercontent.com/743246/39036498-f4eebc5e-447d-11e8-9c52-830b81cef6c0.png">

yah already 20% less for the index...

**Comment by clemsos** [comment]
ok deployed this first change online in 0.9.22 . Things are fast on my side but I guess it depends a lot on the client machine as the fetching is happening client-side.

@tuxun @MaryPek can you test https://box.ludobox.net and let me know if it is any better?

**Comment by MaryPek** [comment]
It's better !
