### ISSUE TITLE
Create new game : needs to be able to choose preselected option

### ISSUE THREAD

**Issue by JulienDcalk** [ludobox/ludobox#36]
Recording is painfull, beeing able to record **type, theme and machines** from preselected or preregistered list of tag

**Comment by clemsos** [comment]
OK, doable. 

@JulienDcalk we need to define these lists though.

- Type : what will be a list of different game types ?
- Machines : we can start with the MIT fablab equipment ? https://trello.com/b/paidmF62/fablab-equipment Maybe some other specific stuff (dices, etc.) ?
- Themes : should this be left as free tagging ? Games can be about virtually anything, looks tricky to define themes, no?

**Comment by clemsos** [comment]
@JulienDcalk didn't we discuss that already? How to solve this ?
