### ISSUE TITLE
Record games in multiple languages

### ISSUE THREAD

**Issue by JulienDcalk** [ludobox/ludobox#39]
Error : `cf: "instance.audience.language does not meet maximum length of 2"`

Impossible to record langageS
exemple of a game with different rules translation (ex: fr,pt, eng), should we make separate folder and merge it later?

**Comment by clemsos** [comment]
Yes, for now when the same game exists in different language, we just treat it as a different games. We can link them together later.

**Comment by clemsos** [comment]
For multilingual games, we should accept multiple languages though

**Comment by clemsos** [comment]
For now, we should just add sth generic like "multilingual" represented by the 2 characters XX or ZZ.

**Comment by clemsos** [comment]
The best thing maybe will be to add the language information in the title . Example : "Cards Against Humanity - FR" ,  "Cards Against Humanity - GR"

**Comment by clemsos** [comment]
See also discussion in #18

**Comment by clemsos** [comment]
OK, we can now add game with the same name if in different language. It will be stored in a folder with the slugified name + the language code as explained in #43 .
