### ISSUE TITLE
50% loss in recording

### ISSUE THREAD

**Issue by JulienDcalk** [ludobox/ludobox#41]
..... ok i spend few hours to register games; 
unfortunetly for now i get half of the job that don't fonction for a unknow reason (i carefully click twice to "submit" button, but it seems that on my side i don't see deposit files on the game collection)
i make a pause for now then

**Comment by clemsos** [comment]
ok I'll check that soon

**Comment by clemsos** [comment]
and yes just hold on adding games now

**Comment by JulienDcalk** [comment]
Exemples of games missing:
-**cards against humanity** (english version) -----> the greek version was recorded cause... i wrote:
 "Cards Agasint Humanity"....
- **Mosqopoly**
- **Metakettle**

**Comment by clemsos** [comment]
```
ludobox@vps372683:~$ ls -l ludobox/data/
total 72
drwxr-xr-x 3 root    root    4096 Apr 20 17:53 barbecue
drwxr-xr-x 4 ludobox ludobox 4096 Feb  6 18:12 borgia-le-jeu-malsain
drwxr-xr-x 3 root    root    4096 Apr  7 17:24 cards-against-humanity
drwxr-xr-x 3 root    root    4096 Apr 25 12:51 cards-agasint-humanity
drwxr-xr-x 3 root    root    4096 Apr  9 12:50 cree-ton-fablab
drwxr-xr-x 3 root    root    4096 Apr  9 13:29 deepsea-desperation
drwxr-xr-x 3 root    root    4096 Mar 30 13:06 galipotes
drwxr-xr-x 3 root    root    4096 Apr 25 15:51 in-it-together
drwxr-xr-x 3 root    root    4096 Apr 25 16:18 kar-attack
drwxr-xr-x 3 root    root    4096 Apr 20 18:40 l-assassin-habite-au-21
drwxr-xr-x 3 root    root    4096 Apr 20 13:40 les-rois-du-tabac
drwxr-xr-x 3 root    root    4096 Apr 20 18:49 menhir
drwxr-xr-x 3 root    root    4096 Apr 20 14:12 organism
drwxr-xr-x 3 root    root    4096 Apr 19 12:56 petit-patapon
-rw-r--r-- 1 ludobox ludobox  231 Feb  6 15:39 README.md
drwxr-xr-x 3 root    root    4096 Mar 30 10:30 secret-hitler
drwxr-xr-x 3 root    root    4096 Apr 20 15:17 xochintlan
drwxr-xr-x 3 root    root    4096 Apr  9 14:10 zone-a-defendre
```

No traces traces of the games on the disk.The logs show nothing... :cry:

My guess is that it is related to the page that does not refresh properly once a game is added. The problem lies with the file upload that does not end properly.  

Did you get any notification when the file upload end?

**Comment by JulienDcalk** [comment]
Ok,
so as far i understand when i drag a file to upload i get only message : "Uploading 1 files..."
is there something else to wait before submiting the all record card ?

**Comment by clemsos** [comment]
The current problem is that there is no feedback about the upload or anything else that relates to the server. I am fixing it with #45 but still need some polishing. I will work on it this afternoon, so you can get back to add games soon.

**Comment by arthurlutz** [comment]
I might have been hit by the same problem when trying to upload some games. One of them is http://box.ludobox.net/games/lego4devops which shows up as a white page. I also tried to upload https://github.com/outofordergames/blocbybloc which didn't work because of too large files I guess.

**Comment by arthurlutz** [comment]
@clemsos on a technical note I would recommend collecting errors with sentry https://github.com/getsentry/sentry which has could be used server side in python and client side in javascript.

**Comment by clemsos** [comment]
@arthurlutz thanks for the feedback ! 

Looks like the game has been properly created on the server

```
('UPLOADED FILES:', [u'Lego4DevOpsV1.1-20170428T074846Z-001.zip'])
path created : /home/ludobox/ludobox/data/lego4devops
```
 but cannot be read on the client (JS crash).

![selection_249](https://cloud.githubusercontent.com/assets/743246/26308124/2962f252-3ef8-11e7-949b-70316a145b00.png)

There is zero log server-side for blocbybloc :/ 

About logs, there is an open issue #11 (the name of the issue say it all !)
Sentry looks cool, I didn't know about it. Will try to add it soon. 
If you have any working example for JS+python logs with sentry I'll take it.

**Comment by arthurlutz** [comment]
For python : https://docs.sentry.io/clients/python/
For javascript : https://docs.sentry.io/clients/javascript/ 
There's even a react integration : https://docs.sentry.io/clients/javascript/integrations/react/

**Comment by clemsos** [comment]
fixed this one : http://box.ludobox.net/games/lego4devops

**Comment by JulienDcalk** [comment]
So, i tried to record a new game with different browser (mozilla, chrome), i try few experiment to find where it begin to be :
-if  i "test" a blank page i get the "5 errors" message
-if i begin to fill the page: untill i get the 5 initial info when i click the "create new game" button i get errors messages, when all are filled i get the "missing file" error message.  
- if i put file: "create new game" button become dead, no more errors messages, and its impossible to even remove the file

**Comment by clemsos** [comment]
Rhaaa... 
Je viens de faire exactement la même chose et ça marche nickel de mon coté.

Tu es sur quel navigateur, quelle version ? Est-ce que tu peux essayer sur un autre navigateur voir si ça marche ou pas?

Si tu ouvres la [console du navigateur](https://www.wickedlysmart.com/hfjsconsole/), est-ce que tu as un message d'erreur ?

**Comment by JulienDcalk** [comment]
alors si j'ai bien compris, j'ai ouvert la console et j'ai decouvert ce message:

Unhandled promise rejection Error: Network Error
Trace de la pile :
e.exports@https://box.ludobox.net/js/bundle.js:29:10887
e.exports/</d.onerror@https://box.ludobox.net/js/bundle.js:29:9685

**Comment by clemsos** [comment]
After some investigation, it looks like the issue was related to file upload --  the file was too big for the server to accept it (<25 Mo). 

I have opened an issue to track this here https://github.com/ludobox/ludobox/issues/88

**Comment by clemsos** [comment]
The upload size limit is solved so I am closing this for now (yeah!)
