### ISSUE TITLE
Editing game > selecting type erases gameplay

### ISSUE THREAD

**Issue by Daenn** [ludobox/ludobox#70]
**How to reproduce**
Edit any game, scroll to see type & gameplay.
Select a gameplay.
Select a type

**Issue**
When you selected a type, the gameplay got removed.

**Request**
These two fields are independent (i.e. choices for gameplay do not change depending on choice in type), so this erasing behavior should be removed.

**Comment by MaryPek** [comment]
Same for me but after i select type and the gameplay erased and i re-selected gameplay, the both stayed.

**Comment by clemsos** [comment]
Yep. Solved in 65a63ce1ec6b4b0cd13457411bb66f90656c31b5
