### ISSUE TITLE
Editing game > adding a tag keeps the text for the next tag

### ISSUE THREAD

**Issue by Daenn** [ludobox/ludobox#71]
**How to reproduce**
Edit any game, scroll down to tag section.
Enter a tag text, press enter.

**Issue**
The text you entered remains into the textarea, so if you want to add multiple texts in a row, you have to erase your previous tag all the time.

**Request**
Please automatically erase the text after saving the tag.

**Comment by Daenn** [comment]
Same behaviour with the authors tags.

By the way, these boxes are counter-intuitive. Would be more clear if they said "write then Enter" instead of "write sth"

**Comment by MaryPek** [comment]
+1 i have pressed enter by habits but i don't know if everyone will do the same
