### ISSUE TITLE
Game page > authors aren't showing

### ISSUE THREAD

**Issue by Daenn** [ludobox/ludobox#74]
**Steps to reproduce**
View any game that has authors (ex: Chtemele) saved (go in edit mode to see them).

**Issue**
The author section in the game is empty.

**Request**
Fix the page so the authors are shown.

**Comment by clemsos** [comment]
sorry @Daenn  can not reproduce :cry: Chtemele is not in the db and I see authors here http://box.ludobox.net/games/game-barbecue-fr
