### ISSUE TITLE
Add Game : missing "components" field (dices, cards, etc.)

### ISSUE THREAD

**Issue by MaryPek** [ludobox/ludobox#79]
Missed the "already material" in the requirement list, type : 54 cards / dices / tokens etc..

**Comment by clemsos** [comment]
Dices, etc are called "components". Here is the list that we currently have : https://github.com/ludobox/ludobox/blob/b7c0531cd35353887f54047d76f12c10af65107c/model/game.json#L299

**Comment by JulienDcalk** [comment]
Game compoments should be the right word for this thing
