### ISSUE TITLE
UI > space between action buttons when editing game

### ISSUE THREAD

**Issue by Daenn** [ludobox/ludobox#84]
*Context*
Edit any game, preferrably using an account that has the rights to validate/reject games.
Go to the bottom, where the action buttons lie (edit/delete/review/validate/reject).

*Issue*
The buttons are all cluttered together, which makes them hard to spot.

*Request*
Please add some space between them, e.g. padding:5px.

**Comment by clemsos** [comment]
![selection_290](https://user-images.githubusercontent.com/743246/31602379-1da8c080-b25d-11e7-8a72-bce0d7b8b831.png)
