### ISSUE TITLE
background image not displayed properly

### ISSUE THREAD

**Issue by Daenn** [ludobox/ludobox#91]
*Context*
Reach the main box's website

*Issue*
As per screenshot, the background image goes under the contents, making everything unreadable.

*Request*
Fix the image's position/size
![box_backgroundissue](https://user-images.githubusercontent.com/2265686/31770368-e3cbaaf8-b4d7-11e7-8602-c5146a0580a5.png)

**Comment by clemsos** [comment]
Woops ! On Firefox ?
